use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::PathBuf;

fn hex_to_bytes(s: &str) -> Option<Vec<u8>> {
    if s.len() % 2 == 0 {
        (0..s.len())
            .step_by(2)
            .map(|i| s.get(i..i + 2).and_then(|sub| u8::from_str_radix(sub, 16).ok()))
            .collect()
    } else {
        None
    }
}

/// Read and parse LoRaWAN keys as HEX strings from an environment variable
fn parse_lorawan_id(val: Option<&str>, var: &str, len: usize) -> Option<String> {
    if let Some(s) = val {
        let l = s.len();
        // Allow empty keys
        if l == 0 {
            return None;
        }
        if l % 2 == 1 || l != 2 * len {
            panic!(
                "Environment variable {} has invalid length: {}, expecting: {}",
                &var,
                l,
                2 * len
            );
        }
        if let Some(v) = hex_to_bytes(s) {
            return Some(format!("Some({:?})", v));
        } else {
            panic!(
                "Unable to parse {} from environment, make sure it's a valid hex string with length {}",
                &var,
                2 * len
            );
        }
    }
    None
}

fn generate_victron_encryption_keys(out: &PathBuf) {
    let path = &out.join("victron_keys.rs");
    let mut file = BufWriter::new(File::create(path).unwrap());

    // Parse encryption keys from environment variables
    // Expected format: VICTRON_KEY_1=... (32 hex characters = 128 bits)
    let mut keys = Vec::new();
    let mut key_idx = 1;

    loop {
        let var_name = format!("VICTRON_KEY_{}", key_idx);
        match env::var(&var_name) {
            Ok(val) => {
                if let Some(key) = parse_victron_encryption_key(&val, &var_name) {
                    keys.push(key);
                    key_idx += 1;
                } else {
                    break;
                }
            }
            Err(_) => break,
        }
    }
    

    // Generate the keys array
    writeln!(
        &mut file,
        "// Generated by build.rs from environment variables"
    )
    .unwrap();

    writeln!(
        &mut file,
        "pub const ENCRYPTION_KEYS: [[u8; 16]; {}] = [",
        keys.len().max(1) // At least 1 key (example key if none provided)
    )
    .unwrap();

    if keys.is_empty() {
        // Provide example key if no keys configured
        writeln!(
            &mut file,
            "    // Example key - REPLACE WITH YOUR ACTUAL KEYS"
        )
        .unwrap();
        writeln!(
            &mut file,
            "    [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],"
        ).unwrap();
    } else {
        for key in &keys {
            writeln!(&mut file, "    {},", key).unwrap();
        }
    }

    writeln!(&mut file, "];").unwrap();
}

/// Parse a hex string encryption key (32 hex chars = 16 bytes)
fn parse_victron_encryption_key(val: &str, var: &str) -> Option<String> {
    let trimmed = val.trim();

    // Allow empty values
    if trimmed.is_empty() {
        return None;
    }

    // Check length (should be 32 hex characters for 128-bit key)
    if trimmed.len() != 32 {
        panic!(
            "Environment variable {} has invalid length: {}, expecting: 32 hex characters (128 bits)",
            var,
            trimmed.len()
        );
    }

    // Parse hex string to bytes
    match hex_to_bytes(trimmed) {
        Some(bytes) => {
            if bytes.len() != 16 {
                panic!(
                    "Environment variable {} parsed to {} bytes, expecting: 16 bytes",
                    var,
                    bytes.len()
                );
            }
            Some(format!(
                "[{}]",
                bytes
                    .iter()
                    .map(|b| format!("0x{:02x}", b))
                    .collect::<Vec<_>>()
                    .join(", ")
            ))
        }
        None => {
            panic!(
                "Unable to parse {} from environment, make sure it's a valid hex string",
                var
            );
        }
    }
}

fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());

    // Load .env file if it exists
    dotenvy::dotenv().ok();

    // Generate LoRaWAN eui and key overrides from environment variables
    {
        let path = &out.join("lorawan_keys.rs");
        let mut file = BufWriter::new(File::create(path).unwrap());

        // Now read from env::var() which will see the loaded .env variables
        let deveui = parse_lorawan_id(env::var("LORA_DEVEUI").ok().as_deref(), "LORA_DEVEUI", 8);
        let appeui = parse_lorawan_id(env::var("LORA_APPEUI").ok().as_deref(), "LORA_APPEUI", 8);
        let appkey = parse_lorawan_id(env::var("LORA_APPKEY").ok().as_deref(), "LORA_APPKEY", 16);

        write!(
            &mut file,
            "{}",
            format_args!(
                "\
            // Generated by build.rs\n\
            const DEVEUI: Option<[u8; 8]> = {};\n\
            const APPEUI: Option<[u8; 8]> = {};\n\
            const APPKEY: Option<[u8; 16]> = {};\n",
                deveui.unwrap_or("None".to_string()),
                appeui.unwrap_or("None".to_string()),
                appkey.unwrap_or("None".to_string()),
            )
        )
        .unwrap();
    }

    // Generate Victron encryption keys from environment variables
    generate_victron_encryption_keys(&out);

    linker_be_nice();
    println!("cargo:rustc-link-arg=-Tdefmt.x");
    // make sure linkall.x is the last linker script (otherwise might cause problems with flip-link)
    println!("cargo:rustc-link-arg=-Tlinkall.x");
}

fn linker_be_nice() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 1 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                "_defmt_timestamp" => {
                    eprintln!();
                    eprintln!(
                        "💡 `defmt` not found - make sure `defmt.x` is added as a linker script and you have included `use defmt_rtt as _;`"
                    );
                    eprintln!();
                }
                "_stack_start" => {
                    eprintln!();
                    eprintln!("💡 Is the linker script `linkall.x` missing?");
                    eprintln!();
                }
                "esp_rtos_initialized" | "esp_rtos_yield_task" | "esp_rtos_task_create" => {
                    eprintln!();
                    eprintln!(
                        "💡 `esp-radio` has no scheduler enabled. Make sure you have initialized `esp-rtos` or provided an external scheduler."
                    );
                    eprintln!();
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!();
                    eprintln!(
                        "💡 `embedded-test` not found - make sure `embedded-test.x` is added as a linker script for tests"
                    );
                    eprintln!();
                }
                _ => (),
            },
            // we don't have anything helpful for "missing-lib" yet
            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        std::env::current_exe().unwrap().display()
    );
}
